vich_uploader:
  db_driver: orm
  mappings:
    equipments_images:
      uri_prefix: "%app.path.equipments_images%"
      upload_destination: "%kernel.project_dir%/public%app.path.equipments_images%"
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
